# Generated by Django 4.2.7 on 2025-11-22 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='The natural language query from the user')),
                ('locality', models.CharField(blank=True, help_text='Extracted locality from the query', max_length=100, null=True)),
                ('year_range', models.CharField(blank=True, help_text='Year range from the query', max_length=50, null=True)),
                ('property_type', models.CharField(blank=True, help_text='Type of property if specified', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, help_text='Generated analysis summary', null=True)),
                ('chart_data', models.JSONField(blank=True, help_text='Chart data in JSON format', null=True)),
            ],
            options={
                'verbose_name_plural': 'Analysis Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CachedAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(help_text='SHA-256 hash of the query parameters', max_length=64, unique=True)),
                ('query_params', models.JSONField(help_text='Query parameters in JSON format')),
                ('result', models.JSONField(help_text='Cached analysis result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0, help_text='Number of times this cache has been accessed')),
            ],
            options={
                'verbose_name_plural': 'Cached Analyses',
                'ordering': ['-last_accessed'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the listing')),
                ('month', models.IntegerField(help_text='Month of the listing')),
                ('locality', models.CharField(help_text='Locality of the property', max_length=100)),
                ('property_type', models.CharField(help_text='Type of property', max_length=50)),
                ('price_per_sqft', models.DecimalField(decimal_places=2, help_text='Price per square foot', max_digits=10)),
                ('size_sqft', models.IntegerField(help_text='Size in square feet')),
                ('total_price_lakhs', models.DecimalField(decimal_places=2, help_text='Total price in lakhs', max_digits=15)),
                ('demand_score', models.IntegerField(help_text='Demand score (0-100)')),
                ('bedrooms', models.IntegerField(blank=True, help_text='Number of bedrooms', null=True)),
                ('bathrooms', models.IntegerField(blank=True, help_text='Number of bathrooms', null=True)),
                ('furnishing', models.CharField(blank=True, help_text='Furnishing status', max_length=20, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='Type of transaction', max_length=20, null=True)),
                ('possession_status', models.CharField(blank=True, help_text='Possession status', max_length=50, null=True)),
                ('builder', models.CharField(blank=True, help_text='Name of the builder', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Property Listings',
                'ordering': ['-year', '-month', 'locality'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('loc_lat', models.FloatField(blank=True, null=True)),
                ('loc_lng', models.FloatField(blank=True, null=True)),
                ('total_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_sold', models.IntegerField(blank=True, null=True)),
                ('flat_sold', models.IntegerField(blank=True, null=True)),
                ('office_sold', models.IntegerField(blank=True, null=True)),
                ('others_sold', models.IntegerField(blank=True, null=True)),
                ('shop_sold', models.IntegerField(blank=True, null=True)),
                ('commercial_sold', models.IntegerField(blank=True, null=True)),
                ('other_sold', models.IntegerField(blank=True, null=True)),
                ('residential_sold', models.IntegerField(blank=True, null=True)),
                ('flat_weighted_avg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('office_weighted_avg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('others_weighted_avg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shop_weighted_avg_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('flat_prevailing_rate_range', models.CharField(blank=True, max_length=100)),
                ('office_prevailing_rate_range', models.CharField(blank=True, max_length=100)),
                ('others_prevailing_rate_range', models.CharField(blank=True, max_length=100)),
                ('shop_prevailing_rate_range', models.CharField(blank=True, max_length=100)),
                ('total_units', models.IntegerField(blank=True, null=True)),
                ('total_carpet_area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('flat_total', models.IntegerField(blank=True, null=True)),
                ('shop_total', models.IntegerField(blank=True, null=True)),
                ('office_total', models.IntegerField(blank=True, null=True)),
                ('others_total', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['final_location', 'year'],
                'unique_together': {('final_location', 'year', 'city')},
            },
        ),
    ]
